import {
  MemoryCollectionItem,
  TimelineMoment,
  MediaDetailItem,
  GraphNodeItem,
  AskQueryResult,
} from '../types';

export const mockMemoryCollection: MemoryCollectionItem[] = [
  {
    id: 'hackathon-2026',
    title: 'Hackathon 2026',
    subtitle: 'Building something worth remembering.',
    date: 'September 24–26, 2026',
    monthYear: 'September 2026',
    location: 'Chennai',
    assetCount: 342,
    videoCount: 18,
    category: 'Projects',
    coverGradient: 'from-[#3B267E] via-[#6D5DFB] to-[#F4A7D8]',
    tags: ['Hackathon', 'AI', 'Innovation', 'Team Zyphra'],
    featured: true,
    isDemo: true,
  },
  {
    id: 'pondicherry-trip',
    title: 'Pondicherry Trip',
    subtitle: 'French colonial streets, sunrise surfs, and coastal dusk.',
    date: 'August 12–16, 2026',
    monthYear: 'August 2026',
    location: 'Pondicherry & White Town',
    assetCount: 186,
    videoCount: 12,
    category: 'Trips',
    coverGradient: 'from-[#69E1D4] via-[#8DDCFF] to-[#6D5DFB]',
    tags: ['Coast', 'Architecture', 'Sunset', 'Cafe Walks'],
  },
  {
    id: 'college-symposium',
    title: 'College Symposium',
    subtitle: 'Keynotes, tech exhibits, and late-night organizing frenzy.',
    date: 'August 02–04, 2026',
    monthYear: 'August 2026',
    location: 'Auditorium Hall 4',
    assetCount: 214,
    videoCount: 14,
    category: 'Events',
    coverGradient: 'from-[#B8A7FF] via-[#6D5DFB] to-[#3B267E]',
    tags: ['Keynote', 'Stage', 'Exhibition', 'Campus'],
  },
  {
    id: 'startup-journey',
    title: 'Startup Journey',
    subtitle: 'From whiteboard scrawls to the first live deploy.',
    date: 'July 15–28, 2026',
    monthYear: 'July 2026',
    location: 'Zyphra Co-lab Studio',
    assetCount: 127,
    videoCount: 9,
    category: 'Projects',
    coverGradient: 'from-[#F4A7D8] via-[#B8A7FF] to-[#6D5DFB]',
    tags: ['Founders', 'Product', 'Milestone', 'Late Night'],
  },
  {
    id: 'family-celebration',
    title: 'Family Celebration',
    subtitle: 'Three generations, traditional feasts, and endless laughter.',
    date: 'June 18–20, 2026',
    monthYear: 'June 2026',
    location: 'Heritage Courtyard',
    assetCount: 238,
    videoCount: 21,
    category: 'Events',
    coverGradient: 'from-[#8DDCFF] via-[#6D5DFB] to-[#3B267E]',
    tags: ['Reunion', 'Tradition', 'Feast', 'Golden Hour'],
  },
];

export const mockTimelineMoments: TimelineMoment[] = [
  {
    id: 'moment-arrival',
    time: '09:12 AM',
    title: 'Arrival',
    description: 'Everyone is here. The day begins with badge pickups, morning coffee, and high spirits.',
    mediaCount: 24,
    mediaType: 'photo',
    tags: ['arrival', 'check-in', 'coffee', 'team'],
    context: 'Entrance foyer and team registration table as the doors opened.',
    coverGradient: 'from-[#6D5DFB] via-[#8576FF] to-[#8DDCFF]',
    secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    scene: 'registration foyer',
    activity: 'attendee check-in & badge retrieval',
    momentType: 'arrival',
    objects: ['registration counter', 'lanyards', 'welcome banner', 'coffee cups'],
    aiInsight: {
      id: 'moment-arrival',
      scene: 'auditorium entrance foyer',
      activity: 'attendee check-in and team greeting',
      objects: ['badges', 'registration desk', 'welcome banners', 'coffee cups'],
      tags: ['arrival', 'check-in', 'morning', 'energy'],
      context: 'Initial gathering as teams checked in and received their participant credentials.',
      momentType: 'arrival',
      description: 'Morning registration foyer buzzing with anticipation as badges are distributed.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_arr_912',
      public_id: 'lumora/hackathon2026/arrival',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1080,
      bytes: 4890000,
      secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T09:12:00Z',
    },
    relatedMomentIds: ['moment-prototype', 'moment-collab'],
  },
  {
    id: 'moment-prototype',
    time: '11:40 AM',
    title: 'Building the Prototype',
    description: 'The team starts bringing the idea to life. Code editor splits and 3D shaders taking shape.',
    mediaCount: 56,
    mediaType: 'photo',
    tags: ['build', 'prototype', 'code', 'architecture'],
    context: 'Hackathon workstation 14 with dual monitors, wireframe sketches, and API mocks.',
    coverGradient: 'from-[#3B267E] via-[#6D5DFB] to-[#69E1D4]',
    secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    scene: 'workstation 14',
    activity: 'deep prototyping & 3D shader engineering',
    momentType: 'breakthrough',
    objects: ['dual monitors', 'laptops', 'wireframe sketches', 'sticky notes'],
    aiInsight: {
      id: 'moment-prototype',
      scene: 'developer workstation pod',
      activity: 'collaborative shader coding and interactive canvas tuning',
      objects: ['laptops', 'mechanical keyboard', 'code display', 'whiteboard'],
      tags: ['prototype', 'code', 'sprint', 'breakthrough'],
      context: 'Deep technical sprint focused on achieving real-time 3D performance.',
      momentType: 'breakthrough',
      description: 'Intense workstation focus as the 3D visual engine compiles successfully.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_proto_1140',
      public_id: 'lumora/hackathon2026/prototype',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1280,
      bytes: 5120000,
      secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T11:40:00Z',
    },
    relatedMomentIds: ['moment-arrival', 'moment-collab', 'moment-presentation'],
  },
  {
    id: 'moment-collab',
    time: '01:30 PM',
    title: 'Team Collaboration',
    description: 'Design, code, and ideas come together over quick lunch bites and rapid feedback iterations.',
    mediaCount: 42,
    mediaType: 'video',
    tags: ['team', 'collaboration', 'design', 'discussion'],
    context: 'Huddled around the laptop testing interactive gestures and audio synchronization.',
    coverGradient: 'from-[#B8A7FF] via-[#F4A7D8] to-[#6D5DFB]',
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    scene: 'breakout table',
    activity: 'cross-functional design review',
    momentType: 'deep collaboration',
    objects: ['shared laptop', 'coffee mugs', 'printed user flows'],
    aiInsight: {
      id: 'moment-collab',
      scene: 'collaborative team lounge',
      activity: 'gesture-driven navigation sync & UI polish',
      objects: ['tabletop screen', 'sketchpad', 'headphones'],
      tags: ['collaboration', 'team', 'design', 'discussion'],
      context: 'Spontaneous team alignment syncing motion transitions and narrative arc.',
      momentType: 'deep collaboration',
      description: 'High-energy team huddle reviewing fluid motion curves and timeline interactions.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_collab_130',
      public_id: 'lumora/hackathon2026/collaboration_reel',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 18.5,
      bytes: 94600000,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T13:30:00Z',
    },
    relatedMomentIds: ['moment-prototype', 'moment-presentation'],
  },
  {
    id: 'moment-presentation',
    time: '04:15 PM',
    title: 'Final Presentation',
    description: 'The moment everything comes together on the main auditorium stage before the judges.',
    mediaCount: 38,
    mediaType: 'video',
    tags: ['presentation', 'stage', 'demo', 'audience'],
    context: 'Live demo of Lumora on the main projection wall with judges watching intently.',
    coverGradient: 'from-[#3B267E] via-[#6D5DFB] to-[#F4A7D8]',
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    scene: 'main auditorium stage',
    activity: 'team live keynote & product demonstration',
    momentType: 'presentation',
    objects: ['projection screen', 'stage microphones', 'podium', 'presentation clicker'],
    aiInsight: {
      id: 'moment-presentation',
      scene: 'grand auditorium stage',
      activity: 'live product demonstration before judging panel',
      objects: ['main stage projector', 'microphones', 'lighting rig'],
      tags: ['presentation', 'stage', 'keynote', 'hackathon', 'spotlight'],
      context: 'Culminating pitch presenting the complete Lumora media intelligence platform.',
      momentType: 'presentation',
      description: 'The team delivering their live product presentation under bright auditorium spotlights.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_pres_415',
      public_id: 'lumora/hackathon2026/stage_demo_reel',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 42.0,
      bytes: 184200000,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T16:15:00Z',
    },
    relatedMomentIds: ['moment-collab', 'moment-results'],
  },
  {
    id: 'moment-results',
    time: '06:30 PM',
    title: 'Results',
    description: 'The final chapter. Celebratory cheers, winner announcement, and shared relief.',
    mediaCount: 65,
    mediaType: 'photo',
    tags: ['results', 'celebration', 'award', 'trophy'],
    context: 'Team holding the Cloudinary AI Hackathon certificate with the mentor panel.',
    coverGradient: 'from-[#69E1D4] via-[#6D5DFB] to-[#3B267E]',
    secure_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    scene: 'stage ceremonial podium',
    activity: 'award recognition and team celebration',
    momentType: 'celebration',
    objects: ['award certificate', 'stage flowers', 'celebratory smiles'],
    aiInsight: {
      id: 'moment-results',
      scene: 'auditorium center stage',
      activity: 'team award presentation and celebration',
      objects: ['winner certificate', 'trophy', 'mentor badges'],
      tags: ['results', 'celebration', 'award', 'victory', 'milestone'],
      context: 'Announcement of Track 3 winners with applause across the auditorium.',
      momentType: 'celebration',
      description: 'Ecstatic team celebration holding the winner award under auditorium confetti.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_res_630',
      public_id: 'lumora/hackathon2026/results_stage',
      resource_type: 'image',
      format: 'jpg',
      width: 2400,
      height: 1600,
      bytes: 16800000,
      secure_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T18:30:00Z',
    },
    relatedMomentIds: ['moment-presentation'],
  },
];

export const mockMediaDetails: Record<string, MediaDetailItem> = {
  'moment-presentation': {
    id: 'moment-presentation',
    filename: 'lumora_stage_demo_4k.mp4',
    type: 'video',
    size: '184.2 MB',
    title: 'Final Presentation',
    time: '04:15 PM',
    context: 'Team presenting the final project on the main stage to jury panel and audience.',
    tags: ['presentation', 'team', 'stage', 'project', 'spotlight'],
    scene: 'main auditorium stage',
    activity: 'live product demonstration before jury panel',
    objects: ['main stage projector', 'microphones', 'lighting rig'],
    momentType: 'presentation',
    aiInsight: {
      id: 'moment-presentation',
      scene: 'grand auditorium stage',
      activity: 'live product demonstration before judging panel',
      objects: ['main stage projector', 'microphones', 'lighting rig'],
      tags: ['presentation', 'stage', 'keynote', 'hackathon', 'spotlight'],
      context: 'Culminating pitch presenting the complete Lumora media intelligence platform.',
      momentType: 'presentation',
      description: 'The team delivering their live product presentation under bright auditorium spotlights.',
      source: 'gemini',
    },
    relatedMoments: ['Building the Prototype', 'Team Collaboration', 'Results'],
    coverGradient: 'from-[#3B267E] via-[#6D5DFB] to-[#F4A7D8]',
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    cloudinaryAsset: {
      asset_id: 'cld_pres_415',
      public_id: 'lumora/hackathon2026/stage_demo_reel',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 42.0,
      bytes: 184200000,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T16:15:00Z',
    },
  },
  'moment-arrival': {
    id: 'moment-arrival',
    filename: 'team_registration_morning.jpg',
    type: 'photo',
    size: '12.4 MB',
    title: 'Arrival',
    time: '09:12 AM',
    context: 'Team members picking up badges and lanyards at the entrance registration desk.',
    tags: ['arrival', 'team', 'morning', 'check-in'],
    scene: 'registration foyer',
    activity: 'attendee check-in & credential collection',
    objects: ['badges', 'registration desk', 'welcome banners', 'coffee cups'],
    momentType: 'arrival',
    aiInsight: {
      id: 'moment-arrival',
      scene: 'auditorium entrance foyer',
      activity: 'attendee check-in and team greeting',
      objects: ['badges', 'registration desk', 'welcome banners', 'coffee cups'],
      tags: ['arrival', 'check-in', 'morning', 'energy'],
      context: 'Initial gathering as teams checked in and received their participant credentials.',
      momentType: 'arrival',
      description: 'Morning registration foyer buzzing with anticipation as badges are distributed.',
      source: 'gemini',
    },
    relatedMoments: ['Building the Prototype', 'Team Collaboration'],
    coverGradient: 'from-[#6D5DFB] via-[#8576FF] to-[#8DDCFF]',
    secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    cloudinaryAsset: {
      asset_id: 'cld_arr_912',
      public_id: 'lumora/hackathon2026/arrival',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1080,
      bytes: 4890000,
      secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T09:12:00Z',
    },
  },
  'moment-prototype': {
    id: 'moment-prototype',
    filename: 'threejs_shader_tuning.png',
    type: 'photo',
    size: '8.1 MB',
    title: 'Building the Prototype',
    time: '11:40 AM',
    context: 'Live debugging of Three.js physical materials and interactive parallax parameters.',
    tags: ['build', 'prototype', 'code', 'threejs'],
    scene: 'workstation pod 14',
    activity: 'deep prototyping & 3D shader engineering',
    objects: ['dual monitors', 'laptops', 'wireframe sketches', 'sticky notes'],
    momentType: 'breakthrough',
    aiInsight: {
      id: 'moment-prototype',
      scene: 'developer workstation pod',
      activity: 'collaborative shader coding and interactive canvas tuning',
      objects: ['laptops', 'mechanical keyboard', 'code display', 'whiteboard'],
      tags: ['prototype', 'code', 'sprint', 'breakthrough'],
      context: 'Deep technical sprint focused on achieving real-time 3D performance.',
      momentType: 'breakthrough',
      description: 'Intense workstation focus as the 3D visual engine compiles successfully.',
      source: 'gemini',
    },
    relatedMoments: ['Arrival', 'Team Collaboration', 'Final Presentation'],
    coverGradient: 'from-[#3B267E] via-[#6D5DFB] to-[#69E1D4]',
    secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    cloudinaryAsset: {
      asset_id: 'cld_proto_1140',
      public_id: 'lumora/hackathon2026/prototype',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1280,
      bytes: 5120000,
      secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T11:40:00Z',
    },
  },
  'moment-collab': {
    id: 'moment-collab',
    filename: 'ui_motion_review_clip.mp4',
    type: 'video',
    size: '94.6 MB',
    title: 'Team Collaboration',
    time: '01:30 PM',
    context: 'Design and frontend huddle refining the 5-stage pipeline and Ask Your Memory responses.',
    tags: ['team', 'collaboration', 'design', 'review'],
    scene: 'breakout table',
    activity: 'cross-functional design review',
    objects: ['shared laptop', 'coffee mugs', 'printed user flows'],
    momentType: 'deep collaboration',
    aiInsight: {
      id: 'moment-collab',
      scene: 'collaborative team lounge',
      activity: 'gesture-driven navigation sync & UI polish',
      objects: ['tabletop screen', 'sketchpad', 'headphones'],
      tags: ['collaboration', 'team', 'design', 'discussion'],
      context: 'Spontaneous team alignment syncing motion transitions and narrative arc.',
      momentType: 'deep collaboration',
      description: 'High-energy team huddle reviewing fluid motion curves and timeline interactions.',
      source: 'gemini',
    },
    relatedMoments: ['Building the Prototype', 'Final Presentation'],
    coverGradient: 'from-[#B8A7FF] via-[#F4A7D8] to-[#6D5DFB]',
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    cloudinaryAsset: {
      asset_id: 'cld_collab_130',
      public_id: 'lumora/hackathon2026/collaboration_reel',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 18.5,
      bytes: 94600000,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T13:30:00Z',
    },
  },
  'moment-results': {
    id: 'moment-results',
    filename: 'team_zyphra_stage_award.jpg',
    type: 'photo',
    size: '16.8 MB',
    title: 'Results',
    time: '06:30 PM',
    context: 'Team celebration upon winning Track 3: Your Media-Savvy Startup with the Lumora platform.',
    tags: ['results', 'award', 'track 3', 'celebration', 'zyphra'],
    scene: 'stage ceremonial podium',
    activity: 'award recognition and team celebration',
    objects: ['award certificate', 'stage flowers', 'celebratory smiles'],
    momentType: 'celebration',
    aiInsight: {
      id: 'moment-results',
      scene: 'auditorium center stage',
      activity: 'team award presentation and celebration',
      objects: ['winner certificate', 'trophy', 'mentor badges'],
      tags: ['results', 'celebration', 'award', 'victory', 'milestone'],
      context: 'Announcement of Track 3 winners with applause across the auditorium.',
      momentType: 'celebration',
      description: 'Ecstatic team celebration holding the winner award under auditorium confetti.',
      source: 'gemini',
    },
    relatedMoments: ['Final Presentation'],
    coverGradient: 'from-[#69E1D4] via-[#6D5DFB] to-[#3B267E]',
    secure_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    cloudinaryAsset: {
      asset_id: 'cld_res_630',
      public_id: 'lumora/hackathon2026/results_stage',
      resource_type: 'image',
      format: 'jpg',
      width: 2400,
      height: 1600,
      bytes: 16800000,
      secure_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      created_at: '2026-09-24T18:30:00Z',
    },
  },
};

export const mockGraphNodes: GraphNodeItem[] = [
  {
    id: 'center',
    label: 'HACKATHON 2026',
    type: 'primary',
    category: 'Center Core',
    x: 50,
    y: 50,
    momentCount: 342,
    description: 'Central media intelligence node uniting all hackathon moments.',
    color: 'from-[#6D5DFB] via-[#8576FF] to-[#3B267E]',
    connections: ['team', 'build', 'presentation', 'event', 'result'],
  },
  {
    id: 'team',
    label: 'TEAM',
    type: 'primary',
    category: 'People & Collaboration',
    x: 24,
    y: 28,
    momentCount: 87,
    description: 'Candid laughs, design whiteboards, and late-night coding huddles.',
    color: 'from-[#6D5DFB] to-[#B8A7FF]',
    connections: ['center', 'people'],
  },
  {
    id: 'build',
    label: 'BUILD',
    type: 'primary',
    category: 'Engineering & Craft',
    x: 76,
    y: 26,
    momentCount: 112,
    description: 'Code snippets, 3D WebGL material tuning, and architectural flow diagrams.',
    color: 'from-[#3B267E] to-[#69E1D4]',
    connections: ['center', 'moments'],
  },
  {
    id: 'presentation',
    label: 'PRESENTATION',
    type: 'primary',
    category: 'Stage & Demo',
    x: 82,
    y: 70,
    momentCount: 48,
    description: 'Stage walkthrough, interactive audience reactions, and jury Q&A.',
    color: 'from-[#F4A7D8] to-[#6D5DFB]',
    connections: ['center', 'places', 'result'],
  },
  {
    id: 'event',
    label: 'EVENT',
    type: 'primary',
    category: 'Atmosphere & Setting',
    x: 20,
    y: 72,
    momentCount: 54,
    description: 'Auditorium ambiance, lunch discussions, mentor advice, and venue energy.',
    color: 'from-[#8DDCFF] to-[#6D5DFB]',
    connections: ['center', 'places'],
  },
  {
    id: 'result',
    label: 'RESULT',
    type: 'primary',
    category: 'Outcome & Joy',
    x: 50,
    y: 84,
    momentCount: 41,
    description: 'Award ceremony, certificate presentation, group photos, and closing smiles.',
    color: 'from-[#69E1D4] to-[#3B267E]',
    connections: ['center', 'presentation'],
  },
  {
    id: 'people',
    label: 'PEOPLE',
    type: 'secondary',
    category: 'Faces & Bonds',
    x: 12,
    y: 44,
    momentCount: 68,
    description: 'Detected 4 team members, 2 mentors, and audience members.',
    color: 'from-[#F4A7D8] to-[#B8A7FF]',
    connections: ['team'],
  },
  {
    id: 'places',
    label: 'PLACES',
    type: 'secondary',
    category: 'Venues',
    x: 88,
    y: 48,
    momentCount: 36,
    description: 'Main auditorium, hackathon lab room 14, and stage podium.',
    color: 'from-[#69E1D4] to-[#8DDCFF]',
    connections: ['presentation', 'event'],
  },
  {
    id: 'moments',
    label: 'MOMENTS',
    type: 'secondary',
    category: 'Key Highlights',
    x: 50,
    y: 16,
    momentCount: 29,
    description: 'Peak emotional moments flagged with high narrative resonance.',
    color: 'from-[#B8A7FF] to-[#6D5DFB]',
    connections: ['build'],
  },
];

export const mockAskQueryResponses: Record<string, AskQueryResult> = {
  'Show our final presentation.': {
    query: 'Show our final presentation.',
    response:
      'Your final presentation happened around 4:15 PM on the main stage. I found 12 related moments from the stage, including 4 high-res photos, 2 4K video clips, and the audio recording of the live product demo.',
    mediaIds: ['moment-presentation', 'moment-results'],
  },
  'Find moments with the whole team.': {
    query: 'Find moments with the whole team.',
    response:
      'I found 28 moments with the whole team together across the weekend. Key clusters include the morning kickoff at 9:12 AM, the design sprint huddle at 1:30 PM, and the award stage ceremony at 6:30 PM.',
    mediaIds: ['moment-arrival', 'moment-collab', 'moment-results'],
  },
  'What happened during the afternoon?': {
    query: 'What happened during the afternoon?',
    response:
      'Between 1:00 PM and 5:00 PM, Lumora recorded 98 assets. The team finalized the prototype, practiced the pitch in the hallway, and presented on the main stage at 4:15 PM.',
    mediaIds: ['moment-collab', 'moment-presentation'],
  },
  'Show the best moments.': {
    query: 'Show the best moments.',
    response:
      'Based on emotional expression analysis and audio energy spikes, the 3 highest resonance moments were: the live stage demo at 4:15 PM, the sudden breakthrough during coding at 11:40 AM, and the celebratory award announcement at 6:30 PM.',
    mediaIds: ['moment-prototype', 'moment-presentation', 'moment-results'],
  },
  'When did we receive the certificate?': {
    query: 'When did we receive the certificate?',
    response:
      'The certificate was handed over at 6:30 PM during the results ceremony on stage. Lumora identified 16 photos and 1 video snippet of the team holding the Cloudinary AI Hackathon certificate.',
    mediaIds: ['moment-results', 'moment-presentation'],
  },
};

export const initialCreateMediaItems: import('../types').UploadingFileItem[] = [
  {
    id: 'f1',
    filename: 'hackathon_kickoff_stage.jpg',
    type: 'photo' as const,
    size: '4.8 MB',
    title: 'Auditorium Kickoff',
    time: '09:15 AM',
    gradient: 'from-[#6D5DFB] to-[#8DDCFF]',
    status: 'success',
    progress: 100,
    secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    aiInsight: {
      id: 'f1',
      scene: 'grand auditorium main hall',
      activity: 'opening ceremony keynote and challenge briefing',
      objects: ['stage lighting', 'main projector screen', 'audience seating'],
      tags: ['kickoff', 'stage', 'keynote', 'event', 'energy'],
      context: 'Official launch of the hackathon with opening remarks and team assembly.',
      momentType: 'arrival',
      description: 'Auditorium bathed in vibrant stage lights as the hackathon is announced open.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_as_kickoff',
      public_id: 'lumora/hackathon_kickoff_stage',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1080,
      bytes: 5033164,
      secure_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
      created_at: '2026-09-24T09:15:00Z',
    },
  },
  {
    id: 'f2',
    filename: 'team_zyphra_whiteboard.jpg',
    type: 'photo' as const,
    size: '6.2 MB',
    title: 'Architecture Diagram',
    time: '10:30 AM',
    gradient: 'from-[#3B267E] to-[#B8A7FF]',
    status: 'success',
    progress: 100,
    secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    aiInsight: {
      id: 'f2',
      scene: 'hacker pod whiteboard area',
      activity: 'system architecture brainstorming & data flow mapping',
      objects: ['whiteboard marker notes', 'system flowchart', 'laptops'],
      tags: ['architecture', 'whiteboard', 'brainstorming', 'planning'],
      context: 'Team outlining the multi-modal pipeline connecting Cloudinary to Gemini.',
      momentType: 'deep collaboration',
      description: 'Hand-drawn pipeline architecture on the glass whiteboard guiding the build.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_as_whiteboard',
      public_id: 'lumora/team_zyphra_whiteboard',
      resource_type: 'image',
      format: 'jpg',
      width: 1920,
      height: 1280,
      bytes: 6501171,
      secure_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
      created_at: '2026-09-24T10:30:00Z',
    },
  },
  {
    id: 'f3',
    filename: 'prototype_demo_screen.mp4',
    type: 'video' as const,
    size: '88.4 MB',
    title: '3D Canvas Shader Test',
    time: '11:45 AM',
    gradient: 'from-[#69E1D4] to-[#6D5DFB]',
    status: 'success',
    progress: 100,
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    aiInsight: {
      id: 'f3',
      scene: 'screen recording workstation',
      activity: 'WebGL physical material simulation & interactive rotation test',
      objects: ['3D canvas view', 'glsl shader inspector', 'debug console'],
      tags: ['threejs', 'shader', 'simulation', 'interactive'],
      context: 'Testing interactive 3D particle kinematics and real-time response curves.',
      momentType: 'breakthrough',
      description: 'Fluid 3D interactive mesh reacting smoothly to user mouse velocity.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_as_shader',
      public_id: 'lumora/prototype_demo_screen',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 18.5,
      bytes: 92694120,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T11:45:00Z',
    },
  },
  {
    id: 'f4',
    filename: 'stage_presentation_final.mp4',
    type: 'video' as const,
    size: '142.1 MB',
    title: 'Live Pitch to Judges',
    time: '04:15 PM',
    gradient: 'from-[#F4A7D8] to-[#3B267E]',
    status: 'success',
    progress: 100,
    secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
    aiInsight: {
      id: 'f4',
      scene: 'main auditorium stage',
      activity: 'live keynote presentation & platform demonstration',
      objects: ['auditorium projector', 'wireless microphone', 'stage lectern'],
      tags: ['presentation', 'stage', 'pitch', 'judges', 'demo'],
      context: 'Presenting the completed Lumora application live to the judge panel and attendees.',
      momentType: 'presentation',
      description: 'The team delivering their live product presentation under bright auditorium spotlights.',
      source: 'gemini',
    },
    cloudinaryAsset: {
      asset_id: 'cld_as_pitch',
      public_id: 'lumora/stage_presentation_final',
      resource_type: 'video',
      format: 'mp4',
      width: 1920,
      height: 1080,
      duration: 42.0,
      bytes: 149000000,
      secure_url: 'https://res.cloudinary.com/demo/video/upload/f_auto,q_auto/dog.mp4',
      created_at: '2026-09-24T16:15:00Z',
    },
  },
];
