export type Route = '/' | '/dashboard' | '/create' | '/memory/demo';

export type CategoryFilter = 'All' | 'Recent' | 'Trips' | 'Events' | 'Projects';

export interface CloudinaryAsset {
  asset_id: string;
  public_id: string;
  resource_type: 'image' | 'video' | 'raw';
  format: string;
  width: number;
  height: number;
  duration?: number;
  bytes: number;
  secure_url: string;
  created_at: string;
}

/**
 * Structured AI Media Insight generated by Gemini Vision Understanding Engine
 */
export interface MediaInsight {
  id: string;
  scene: string;
  activity: string;
  objects: string[];
  tags: string[];
  context: string;
  momentType: string;
  description: string;
  confidence?: number;
  source?: 'gemini' | 'heuristic';
  analyzedAt?: string;
}

export interface UploadingFileItem {
  id: string;
  file?: File;
  filename: string;
  type: 'photo' | 'video';
  size: string;
  title: string;
  time: string;
  gradient: string;
  progress: number; // 0 to 100
  status: 'idle' | 'uploading' | 'processing' | 'success' | 'error';
  errorMessage?: string;
  cloudinaryAsset?: CloudinaryAsset;
  previewUrl?: string;
  secure_url?: string;
  aiInsight?: MediaInsight;
}

export interface MemoryCollectionItem {
  id: string;
  title: string;
  subtitle: string;
  date: string;
  monthYear: string;
  location: string;
  assetCount: number;
  videoCount: number;
  category: 'Trips' | 'Events' | 'Projects';
  coverGradient: string;
  coverImageUrl?: string;
  tags: string[];
  featured?: boolean;
  isDemo?: boolean;
  mediaItems?: UploadingFileItem[];
  timelineMoments?: TimelineMoment[];
  graphNodes?: GraphNodeItem[];
  chapters?: StoryChapter[];
  clusters?: MemoryCluster[];
  storyCapsules?: MemoryStoryCapsule[];
  keyMomentIds?: string[];
  aiSummary?: string;
  mood?: string;
}

export interface StoryMoment {
  id: string;
  title: string;
  description: string;
  mediaIds: string[];
  timestamp?: string;
  importance: 'high' | 'medium';
}

export interface StoryChapter {
  id: string;
  title: string;
  description: string;
  mediaIds: string[];
  momentIds: string[];
  order: number;
  chapterNumber?: string;
  timeRange?: string;
  momentCount?: number;
  coverGradient?: string;
  secure_url?: string;
}

export interface MemoryStoryCapsule {
  id: string;
  ownerId: string;
  clusterId: string;
  title: string;
  subtitle?: string;
  summary: string;
  mediaIds: string[];
  momentIds: string[];
  chapters: StoryChapter[];
  keyMoments: StoryMoment[];
  dominantActivities: string[];
  dominantTags: string[];
  timeRange?: {
    start?: string;
    end?: string;
  };
  location?: string;
  confidence: 'high' | 'medium' | 'low';
  createdAt: string;
  updatedAt: string;
}

export interface MemoryCluster {
  id: string;
  ownerId: string;
  memoryId?: string;
  title: string;
  subtitle?: string;
  narrativeSummary?: string;
  mediaIds: string[];
  momentIds: string[];
  dominantTags: string[];
  dominantActivities: string[];
  timeRange?: {
    start?: string;
    end?: string;
  };
  location?: string;
  confidence: 'high' | 'medium' | 'low';
  coverImageUrl?: string;
  storyCapsule?: MemoryStoryCapsule;
  createdAt?: string;
  updatedAt?: string;
}

export interface TimelineMoment {
  id: string;
  time: string;
  title: string;
  description: string;
  mediaCount: number;
  mediaType: 'photo' | 'video';
  tags: string[];
  context: string;
  coverGradient: string;
  secure_url?: string;
  cloudinaryAsset?: CloudinaryAsset;
  relatedMomentIds: string[];
  scene?: string;
  momentType?: string;
  objects?: string[];
  activity?: string;
  aiInsight?: MediaInsight;
  significanceScore?: number;
}

export interface MediaDetailItem {
  id: string;
  filename: string;
  type: 'photo' | 'video';
  size: string;
  title: string;
  time: string;
  context: string;
  tags: string[];
  relatedMoments: string[];
  coverGradient: string;
  secure_url?: string;
  cloudinaryAsset?: CloudinaryAsset;
  scene?: string;
  activity?: string;
  objects?: string[];
  momentType?: string;
  aiInsight?: MediaInsight;
}

export interface GraphNodeItem {
  id: string;
  label: string;
  type: 'primary' | 'secondary';
  category: string;
  x: number; // percentage
  y: number; // percentage
  momentCount: number;
  description: string;
  color: string;
  connections: string[];
}

export interface AskQueryResult {
  query: string;
  response: string;
  mediaIds: string[];
}

export interface MemoryAnswer {
  answer: string;
  confidence: 'high' | 'medium' | 'low';
  momentIds: string[];
  mediaIds: string[];
  followUps: string[];
  relevantGraphNodes?: string[];
  temporalAnchor?: string;
  evidenceSummary?: string;
}

export interface ConversationTurn {
  id: string;
  user: string;
  lumora: string;
  confidence: 'high' | 'medium' | 'low';
  momentIds: string[];
  mediaIds: string[];
  followUps: string[];
  relevantGraphNodes?: string[];
  timestamp: string;
}

// Unified Memory Intelligence Knowledge Model (Module 3C)
export interface Moment extends TimelineMoment {
  timestamp?: string;
  mediaIds?: string[];
}

export interface MediaAsset extends MediaDetailItem {
  timestamp?: string;
}

export interface MemoryKnowledgeBase {
  id: string;
  title: string;
  date: string;
  location?: string;
  media: MediaAsset[];
  moments: Moment[];
  insights: MediaInsight[];
  graphRelationships: GraphNodeItem[];
}
